### PR TITLE
Remove unnecessary compass import in BS3 accessibility layer; closes #99

### LINKED ISSUE #97: Accessibility version
https://github.com/rstudio/bootstraplib/pull/92#discussion_r486582986

### LINKED ISSUE #99: lumen@3 is currently broken
Due to some weird interaction with the accessibility Sass

```r
> bootstrap("lumen@3")
Error in compile_data(as_sass(input), options) : 
  Error: Undefined operation: "prefix-usage(browser-prefixes(browsers()), css-transitions, (full-support:true),(partial-support:true)) gt 0.1".
        on line 324:7 of ../../Library/R/4.0/library/bootstraplib/lib/bootstrap-accessibility-plugin/src/sass/compass/_support.scss, in function `use-prefix`
        from line 208:33 of ../../Library/R/4.0/library/bootstraplib/lib/bootstrap-accessibility-plugin/src/sass/compass/_support.scss, in function `prefixes-for-capability`
        from line 218:40 of ../../Library/R/4.0/library/bootstraplib/lib/bootstrap-accessibility-plugin/src/sass/compass/_support.scss, in mixin `with-each-prefix`
        from line 147:12 of ../../Library/R/4.0/library/bootstraplib/lib/bootstrap-accessibility-plugin/src/sass/compass/css3/_transition.scss, in mixin `transition`
        from line 310:14 of ../../Library/R/4.0/library/bootstraplib/lib/bootswatch3/lumen/_bootswatch.scss
        from line 52:9 of stdin
>>   @if $usage > $threshold {

   ------^
```

### PR DESCRIPTION
**Pull request by cpsievert**
Closes #97 and #99

### CODE REVIEW

File: tools/yarn_install.R [hunk 1]
```diff
@@ -10,6 +10,22 @@ withr::with_dir("inst", system("yarn install"))
...
+# Get rid of peer dependencies that we don't need
+# ----------------------------------------------------------------------
+
+# Not necessary dependences brought in by bootwswatch (at least in v4.5.2)
+unlink("inst/lib/http-parser-js", recursive = TRUE)
+unlink("inst/lib/safe-buffer", recursive = TRUE)
+unlink("inst/lib/websocket-driver", recursive = TRUE)
+unlink("inst/lib/websocket-extensions", recursive = TRUE)
+
+# jquery comes in via jquerylib
```
Comment (schloerke) [inline tools/yarn_install.R:23]:
```suggestion
# jquery comes in via jquerylib (R package)
```

**Review by schloerke — APPROVED** [review]
